import { Inter } from "next/font/google";
import "./globals.css";
import { PostProvider } from "@/context/PostContext";
import { TodoProvider } from "@/context/TodoContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PostProvider>
          <TodoProvider>

            <div>
              {children}
            </div>
          </TodoProvider>

        </PostProvider>
      </body>
    </html>
  );
}
